
var Module = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  return (
function(Module) {
  Module = Module || {};

var c;c||(c=typeof Module !== 'undefined' ? Module : {});var n={},q;for(q in c)c.hasOwnProperty(q)&&(n[q]=c[q]);c.arguments=[];c.thisProgram="./this.program";c.quit=function(a,b){throw b;};c.preRun=[];c.postRun=[];var t="";function u(a){return c.locateFile?c.locateFile(a,t):t+a}t=__dirname+"/";var v,w;c.read=function(a,b){v||(v=require("fs"));w||(w=require("path"));a=w.normalize(a);a=v.readFileSync(a);return b?a:a.toString()};
c.readBinary=function(a){a=c.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(c.thisProgram=process.argv[1].replace(/\\/g,"/"));c.arguments=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof x))throw a;});process.on("unhandledRejection",y);c.quit=function(a){process.exit(a)};c.inspect=function(){return"[Emscripten Module object]"};
var z=c.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),A=c.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||z);for(q in n)n.hasOwnProperty(q)&&(c[q]=n[q]);n=void 0;function aa(a){var b;b||(b=16);return Math.ceil(a/b)*b}var ba={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},tempRet0=0,B=!1;function assert(a,b){a||y("Assertion failed: "+b)}
function ca(a){var b=c["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}var ia={stackSave:function(){da()},stackRestore:function(){ea()},arrayToC:function(a){var b=fa(a.length);C.set(a,b);return b},stringToC:function(a){var b=0;if(null!==a&&void 0!==a&&0!==a){var e=(a.length<<2)+1;b=fa(e);ha(a,b,e)}return b}},ja={string:ia.stringToC,array:ia.arrayToC};
function ka(a){var b;if(0===b||!a)return"";for(var e=0,d,f=0;;){d=D[a+f>>0];e|=d;if(0==d&&!b)break;f++;if(b&&f==b)break}b||(b=f);d="";if(128>e){for(;0<b;)e=String.fromCharCode.apply(String,D.subarray(a,a+Math.min(b,1024))),d=d?d+e:e,a+=1024,b-=1024;return d}return E(a)}var la="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ma(a,b){for(var e=b;a[e];)++e;if(16<e-b&&a.subarray&&la)return la.decode(a.subarray(b,e));for(e="";;){var d=a[b++];if(!d)return e;if(d&128){var f=a[b++]&63;if(192==(d&224))e+=String.fromCharCode((d&31)<<6|f);else{var g=a[b++]&63;if(224==(d&240))d=(d&15)<<12|f<<6|g;else{var h=a[b++]&63;if(240==(d&248))d=(d&7)<<18|f<<12|g<<6|h;else{var k=a[b++]&63;if(248==(d&252))d=(d&3)<<24|f<<18|g<<12|h<<6|k;else{var p=a[b++]&63;d=(d&1)<<30|f<<24|g<<18|h<<12|k<<6|p}}}65536>d?e+=String.fromCharCode(d):(d-=
65536,e+=String.fromCharCode(55296|d>>10,56320|d&1023))}}else e+=String.fromCharCode(d)}}function E(a){return ma(D,a)}
function ha(a,b,e){var d=D;if(0<e){e=b+e-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var h=a.charCodeAt(++f);g=65536+((g&1023)<<10)|h&1023}if(127>=g){if(b>=e)break;d[b++]=g}else{if(2047>=g){if(b+1>=e)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=e)break;d[b++]=224|g>>12}else{if(2097151>=g){if(b+3>=e)break;d[b++]=240|g>>18}else{if(67108863>=g){if(b+4>=e)break;d[b++]=248|g>>24}else{if(b+5>=e)break;d[b++]=252|g>>30;d[b++]=128|g>>24&63}d[b++]=128|g>>18&63}d[b++]=128|g>>
12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0}}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function F(a,b){0<a%b&&(a+=b-a%b);return a}var buffer,C,D,G,na,H,I,oa,pa;function qa(){c.HEAP8=C=new Int8Array(buffer);c.HEAP16=G=new Int16Array(buffer);c.HEAP32=H=new Int32Array(buffer);c.HEAPU8=D=new Uint8Array(buffer);c.HEAPU16=na=new Uint16Array(buffer);c.HEAPU32=I=new Uint32Array(buffer);c.HEAPF32=oa=new Float32Array(buffer);c.HEAPF64=pa=new Float64Array(buffer)}
var J,K,ra,L,sa,ta,M;J=K=ra=L=sa=ta=M=0;c.reallocBuffer||(c.reallocBuffer=function(a){try{var b=C;var e=new ArrayBuffer(a);(new Int8Array(e)).set(b)}catch(d){return!1}return ua(e)?e:!1});var va;try{va=Function.prototype.call.bind(Object.getOwnPropertyDescriptor(ArrayBuffer.prototype,"byteLength").get),va(new ArrayBuffer(4))}catch(a){va=function(b){return b.byteLength}}var wa=c.TOTAL_STACK||5242880,N=c.TOTAL_MEMORY||16777216;
N<wa&&A("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+N+"! (TOTAL_STACK="+wa+")");c.buffer?buffer=c.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(c.wasmMemory=new WebAssembly.Memory({initial:N/65536}),buffer=c.wasmMemory.buffer):buffer=new ArrayBuffer(N),c.buffer=buffer);qa();
function O(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var e=b.L;"number"===typeof e?void 0===b.G?c.dynCall_v(e):c.dynCall_vi(e,b.G):e(void 0===b.G?null:b.G)}}}var xa=[],ya=[],za=[],Aa=[],Ba=[],Ca=!1;function Da(){var a=c.preRun.shift();xa.unshift(a)}var P=0,Ea=null,Q=null;c.preloadedImages={};c.preloadedAudios={};function R(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){return new Promise(function(a){a:{try{if(c.wasmBinary){var b=new Uint8Array(c.wasmBinary);break a}if(c.readBinary){b=c.readBinary(d);break a}throw"both async and sync fetching of the wasm failed";}catch(r){y(r)}b=void 0}a(b)})}function b(b){function e(a){h=a.exports;if(h.memory){a=h.memory;var b=c.buffer;a.byteLength<b.byteLength&&A("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);
c.buffer=buffer=a;qa()}c.asm=h;c.usingWasm=!0;P--;c.monitorRunDependencies&&c.monitorRunDependencies(P);0==P&&(null!==Ea&&(clearInterval(Ea),Ea=null),Q&&(a=Q,Q=null,a()))}function f(a){e(a.instance)}function l(b){a().then(function(a){return WebAssembly.instantiate(a,g)}).then(b,function(a){A("failed to asynchronously prepare wasm: "+a);y(a)})}if("object"!==typeof WebAssembly)return A("no native wasm support detected"),!1;if(!(c.wasmMemory instanceof WebAssembly.Memory))return A("no native wasm Memory in use"),
!1;b.memory=c.wasmMemory;g.global={NaN:NaN,Infinity:Infinity};g["global.Math"]=Math;g.env=b;P++;c.monitorRunDependencies&&c.monitorRunDependencies(P);if(c.instantiateWasm)try{return c.instantiateWasm(g,e)}catch(Ta){return A("Module.instantiateWasm callback failed with error: "+Ta),!1}c.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||R(d)||"function"!==typeof fetch?l(f):WebAssembly.instantiateStreaming(fetch(d,{credentials:"same-origin"}),g).then(f,function(a){A("wasm streaming compile failed: "+
a);A("falling back to ArrayBuffer instantiation");l(f)});return{}}var e="ColorQuantizer.wast",d="ColorQuantizer.wasm",f="ColorQuantizer.temp.asm.js";R(e)||(e=u(e));R(d)||(d=u(d));R(f)||(f=u(f));var g={global:null,env:null,asm2wasm:ba,parent:c},h=null;c.asmPreload=c.asm;var k=c.reallocBuffer;c.reallocBuffer=function(a){if("asmjs"===p)var b=k(a);else a:{a=F(a,c.usingWasm?65536:16777216);var d=c.buffer.byteLength;if(c.usingWasm)try{b=-1!==c.wasmMemory.grow((a-d)/65536)?c.buffer=c.wasmMemory.buffer:null;
break a}catch(db){b=null;break a}b=void 0}return b};var p="";c.asm=function(a,d){if(!d.table){a=c.wasmTableSize;void 0===a&&(a=1024);var e=c.wasmMaxTableSize;d.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==e?new WebAssembly.Table({initial:a,maximum:e,element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):Array(a);c.wasmTable=d.table}d.__memory_base||(d.__memory_base=c.STATIC_BASE);d.__table_base||(d.__table_base=0);d=b(d);assert(d,"no binaryen method succeeded.");
return d}})();J=1024;K=J+5824;ya.push({L:function(){Fa()}});c.STATIC_BASE=J;c.STATIC_BUMP=5824;K+=16;var Ga=[null,[],[]],S=0;function T(){S+=4;return H[S-4>>2]}var Ha={};function Ia(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ja=void 0;function U(a){for(var b="";D[a];)b+=Ja[D[a++]];return b}var Ka={},La={},Ma={};
function Na(a,b){if(void 0===a)a="_unknown";else{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var e=a.charCodeAt(0);a=48<=e&&57>=e?"_"+a:a}return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Oa(a){var b=Error,e=Na(a,function(b){this.name=a;this.message=b;b=Error(b).stack;void 0!==b&&(this.stack=this.toString()+"\n"+b.replace(/^Error(:[^\n]*)?\n/,""))});e.prototype=Object.create(b.prototype);e.prototype.constructor=e;e.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return e}var Pa=void 0;function V(a){throw new Pa(a);}
function W(a,b,e){e=e||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||V('type "'+d+'" must have a positive integer typeid pointer');if(La.hasOwnProperty(a)){if(e.O)return;V("Cannot register type '"+d+"' twice")}La[a]=b;delete Ma[a];Ka.hasOwnProperty(a)&&(b=Ka[a],delete Ka[a],b.forEach(function(a){a()}))}var Qa=[],X=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function Ra(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Qa.length?Qa.pop():X.length;X[b]={P:1,value:a};return b}}function Sa(a){return this.fromWireType(I[a>>2])}function Ua(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Va(a,b){switch(b){case 2:return function(a){return this.fromWireType(oa[a>>2])};case 3:return function(a){return this.fromWireType(pa[a>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Wa(a,b,e){switch(b){case 0:return e?function(a){return C[a]}:function(a){return D[a]};case 1:return e?function(a){return G[a>>1]}:function(a){return na[a>>1]};case 2:return e?function(a){return H[a>>2]}:function(a){return I[a>>2]};default:throw new TypeError("Unknown integer type: "+a);}}for(var Xa=Array(256),Y=0;256>Y;++Y)Xa[Y]=String.fromCharCode(Y);Ja=Xa;Pa=c.BindingError=Oa("BindingError");c.InternalError=Oa("InternalError");
c.count_emval_handles=function(){for(var a=0,b=5;b<X.length;++b)void 0!==X[b]&&++a;return a};c.get_first_emval=function(){for(var a=5;a<X.length;++a)if(void 0!==X[a])return X[a];return null};var Ya=K;K=K+4+15&-16;M=Ya;ra=L=aa(K);sa=ra+wa;ta=aa(sa);H[M>>2]=ta;c.wasmTableSize=30;c.wasmMaxTableSize=30;c.J={};
c.K={g:y,v:function(){var a=c.usingWasm?65536:16777216,b=2147483648-a;if(H[M>>2]>b)return!1;var e=N;for(N=Math.max(N,16777216);N<H[M>>2];)536870912>=N?N=F(2*N,a):N=Math.min(F((3*N+2147483648)/4,a),b);a=c.reallocBuffer(N);if(!a||a.byteLength!=N)return N=e,!1;c.buffer=buffer=a;qa();return!0},p:function(){return N},f:function(a){tempRet0=a},c:function(){return tempRet0},o:function(){y("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+N+
", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")},i:function(a){c.___errno_location&&(H[c.___errno_location()>>2]=a);return a},n:function(a,b){S=b;try{var e=Ha.M();T();var d=T(),f=T(),g=T();FS.S(e,d,g);H[f>>2]=e.position;e.N&&0===d&&0===g&&(e.N=null);return 0}catch(h){return"undefined"!==typeof FS&&h instanceof FS.H||y(h),-h.I}},h:function(a,b){S=b;try{var e=
T(),d=T(),f=T();for(b=a=0;b<f;b++){for(var g=H[d+8*b>>2],h=H[d+(8*b+4)>>2],k=0;k<h;k++){var p=e,l=D[g+k],m=Ga[p];assert(m);0===l||10===l?((1===p?z:A)(ma(m,0)),m.length=0):m.push(l)}a+=h}return a}catch(r){return"undefined"!==typeof FS&&r instanceof FS.H||y(r),-r.I}},m:function(a,b){S=b;try{var e=Ha.M();FS.close(e);return 0}catch(d){return"undefined"!==typeof FS&&d instanceof FS.H||y(d),-d.I}},u:function(a,b,e,d,f){var g=Ia(e);b=U(b);W(a,{name:b,fromWireType:function(a){return!!a},toWireType:function(a,
b){return b?d:f},argPackAdvance:8,readValueFromPointer:function(a){if(1===e)var d=C;else if(2===e)d=G;else if(4===e)d=H;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(d[a>>g])},F:null})},t:function(a,b){b=U(b);W(a,{name:b,fromWireType:function(a){var b=X[a].value;4<a&&0===--X[a].P&&(X[a]=void 0,Qa.push(a));return b},toWireType:function(a,b){return Ra(b)},argPackAdvance:8,readValueFromPointer:Sa,F:null})},l:function(a,b,e){e=Ia(e);b=U(b);W(a,{name:b,fromWireType:function(a){return a},
toWireType:function(a,b){if("number"!==typeof b&&"boolean"!==typeof b)throw new TypeError('Cannot convert "'+Ua(b)+'" to '+this.name);return b},argPackAdvance:8,readValueFromPointer:Va(b,e),F:null})},e:function(a,b,e,d,f){function g(a){return a}b=U(b);-1===f&&(f=4294967295);var h=Ia(e);if(0===d){var k=32-8*e;g=function(a){return a<<k>>>k}}var p=-1!=b.indexOf("unsigned");W(a,{name:b,fromWireType:g,toWireType:function(a,e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+
Ua(e)+'" to '+this.name);if(e<d||e>f)throw new TypeError('Passing a number "'+Ua(e)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+f+"]!");return p?e>>>0:e|0},argPackAdvance:8,readValueFromPointer:Wa(b,h,0!==d),F:null})},d:function(a,b,e){function d(a){a>>=2;var b=I;return new f(b.buffer,b[a+1],b[a])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];e=U(e);W(a,{name:e,fromWireType:d,argPackAdvance:8,
readValueFromPointer:d},{O:!0})},k:function(a,b){b=U(b);var e="std::string"===b;W(a,{name:b,fromWireType:function(a){var b=I[a>>2];if(e){var d=D[a+4+b],h=0;0!=d&&(h=d,D[a+4+b]=0);var k=a+4;for(d=0;d<=b;++d){var p=a+4+d;if(0==D[p]){k=E(k);if(void 0===l)var l=k;else l+=String.fromCharCode(0),l+=k;k=p+1}}0!=h&&(D[a+4+b]=h)}else{l=Array(b);for(d=0;d<b;++d)l[d]=String.fromCharCode(D[a+4+d]);l=l.join("")}Z(a);return l},toWireType:function(a,b){b instanceof ArrayBuffer&&(b=new Uint8Array(b));var d="string"===
typeof b;d||b instanceof Uint8Array||b instanceof Uint8ClampedArray||b instanceof Int8Array||V("Cannot pass non-string to std::string");var f=(e&&d?function(){for(var a=0,d=0;d<b.length;++d){var e=b.charCodeAt(d);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|b.charCodeAt(++d)&1023);127>=e?++a:a=2047>=e?a+2:65535>=e?a+3:2097151>=e?a+4:67108863>=e?a+5:a+6}return a}:function(){return b.length})(),k=Za(4+f+1);I[k>>2]=f;if(e&&d)ha(b,k+4,f+1);else if(d)for(d=0;d<f;++d){var p=b.charCodeAt(d);255<p&&(Z(k),
V("String has UTF-16 code units that do not fit in 8 bits"));D[k+4+d]=p}else for(d=0;d<f;++d)D[k+4+d]=b[d];null!==a&&a.push(Z,k);return k},argPackAdvance:8,readValueFromPointer:Sa,F:function(a){Z(a)}})},s:function(a,b,e){e=U(e);if(2===b){var d=function(){return na};var f=1}else 4===b&&(d=function(){return I},f=2);W(a,{name:e,fromWireType:function(a){for(var b=d(),e=I[a>>2],g=Array(e),l=a+4>>f,m=0;m<e;++m)g[m]=String.fromCharCode(b[l+m]);Z(a);return g.join("")},toWireType:function(a,e){var g=d(),h=
e.length,l=Za(4+h*b);I[l>>2]=h;for(var m=l+4>>f,r=0;r<h;++r)g[m+r]=e.charCodeAt(r);null!==a&&a.push(Z,l);return l},argPackAdvance:8,readValueFromPointer:Sa,F:function(a){Z(a)}})},r:function(a,b){b=U(b);W(a,{R:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},q:function(a,b,e){D.set(D.subarray(b,b+e),a);return a},j:function(a){if(!c.noExitRuntime&&(B=!0,L=$a,O(Aa),c.onExit))c.onExit(a);c.quit(a,new x(a))},a:M,b:L};var ab=c.asm(c.J,c.K,buffer);c.asm=ab;
var Fa=c.__GLOBAL__sub_I_bind_cpp=function(){return c.asm.w.apply(null,arguments)};c.___getTypeName=function(){return c.asm.x.apply(null,arguments)};var ua=c._emscripten_replace_memory=function(){return c.asm._emscripten_replace_memory.apply(null,arguments)},Z=c._free=function(){return c.asm.y.apply(null,arguments)};c._getImageThemeColor=function(){return c.asm.z.apply(null,arguments)};
var Za=c._malloc=function(){return c.asm.A.apply(null,arguments)},fa=c.stackAlloc=function(){return c.asm.C.apply(null,arguments)},ea=c.stackRestore=function(){return c.asm.D.apply(null,arguments)},da=c.stackSave=function(){return c.asm.E.apply(null,arguments)};c.dynCall_vi=function(){return c.asm.B.apply(null,arguments)};c.asm=ab;
c.cwrap=function(a,b,e,d){e=e||[];var f=e.every(function(a){return"number"===a});return"string"!==b&&f&&!d?ca(a):function(){var d=e,f=arguments,k=ca(a),p=[],l=0;if(f)for(var m=0;m<f.length;m++){var r=ja[d[m]];r?(0===l&&(l=da()),p[m]=r(f[m])):p[m]=f[m]}d=k.apply(null,p);d="string"===b?ka(d):"boolean"===b?!!d:d;0!==l&&ea(l);return d}};c.UTF8ToString=E;c.then=function(a){if(c.calledRun)a(c);else{var b=c.onRuntimeInitialized;c.onRuntimeInitialized=function(){b&&b();a(c)}}return c};
function x(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}x.prototype=Error();x.prototype.constructor=x;var $a;Q=function bb(){c.calledRun||cb();c.calledRun||(Q=bb)};
function cb(){function a(){if(!c.calledRun&&(c.calledRun=!0,!B)){Ca||(Ca=!0,O(ya));O(za);if(c.onRuntimeInitialized)c.onRuntimeInitialized();if(c.postRun)for("function"==typeof c.postRun&&(c.postRun=[c.postRun]);c.postRun.length;){var a=c.postRun.shift();Ba.unshift(a)}O(Ba)}}if(!(0<P)){if(c.preRun)for("function"==typeof c.preRun&&(c.preRun=[c.preRun]);c.preRun.length;)Da();O(xa);0<P||c.calledRun||(c.setStatus?(c.setStatus("Running..."),setTimeout(function(){setTimeout(function(){c.setStatus("")},1);
a()},1)):a())}}c.run=cb;function y(a){if(c.onAbort)c.onAbort(a);void 0!==a?(z(a),A(a),a=JSON.stringify(a)):a="";B=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}c.abort=y;if(c.preInit)for("function"==typeof c.preInit&&(c.preInit=[c.preInit]);0<c.preInit.length;)c.preInit.pop()();c.noExitRuntime=!0;cb();


  return Module;
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
    module.exports = Module;
  else if (typeof define === 'function' && define['amd'])
    define([], function() { return Module; });
  else if (typeof exports === 'object')
    exports["Module"] = Module;
  