
var Module = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  return (
function(Module) {
  Module = Module || {};

var c;c||(c=typeof Module !== 'undefined' ? Module : {});var n={},p;for(p in c)c.hasOwnProperty(p)&&(n[p]=c[p]);c.arguments=[];c.thisProgram="./this.program";c.quit=function(a,b){throw b;};c.preRun=[];c.postRun=[];var r="";function t(a){return c.locateFile?c.locateFile(a,r):r+a}r=__dirname+"/";var u,v;c.read=function(a,b){u||(u=require("fs"));v||(v=require("path"));a=v.normalize(a);a=u.readFileSync(a);return b?a:a.toString()};
c.readBinary=function(a){a=c.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(c.thisProgram=process.argv[1].replace(/\\/g,"/"));c.arguments=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof w))throw a;});process.on("unhandledRejection",y);c.quit=function(a){process.exit(a)};c.inspect=function(){return"[Emscripten Module object]"};
var z=c.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),A=c.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||z);for(p in n)n.hasOwnProperty(p)&&(c[p]=n[p]);n=void 0;function aa(a){var b;b||(b=16);return Math.ceil(a/b)*b}var ba={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},B=!1;function assert(a,b){a||y("Assertion failed: "+b)}
function ca(a){var b=c["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}var ia={stackSave:function(){da()},stackRestore:function(){ea()},arrayToC:function(a){var b=fa(a.length);C.set(a,b);return b},stringToC:function(a){var b=0;if(null!==a&&void 0!==a&&0!==a){var e=(a.length<<2)+1;b=fa(e);ha(a,b,e)}return b}},ja={string:ia.stringToC,array:ia.arrayToC};
function ka(a){var b;if(0===b||!a)return"";for(var e=0,d,f=0;;){d=D[a+f>>0];e|=d;if(0==d&&!b)break;f++;if(b&&f==b)break}b||(b=f);d="";if(128>e){for(;0<b;)e=String.fromCharCode.apply(String,D.subarray(a,a+Math.min(b,1024))),d=d?d+e:e,a+=1024,b-=1024;return d}return E(a)}var la="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ma(a,b){for(var e=b;a[e];)++e;if(16<e-b&&a.subarray&&la)return la.decode(a.subarray(b,e));for(e="";;){var d=a[b++];if(!d)return e;if(d&128){var f=a[b++]&63;if(192==(d&224))e+=String.fromCharCode((d&31)<<6|f);else{var g=a[b++]&63;if(224==(d&240))d=(d&15)<<12|f<<6|g;else{var h=a[b++]&63;if(240==(d&248))d=(d&7)<<18|f<<12|g<<6|h;else{var k=a[b++]&63;if(248==(d&252))d=(d&3)<<24|f<<18|g<<12|h<<6|k;else{var m=a[b++]&63;d=(d&1)<<30|f<<24|g<<18|h<<12|k<<6|m}}}65536>d?e+=String.fromCharCode(d):(d-=
65536,e+=String.fromCharCode(55296|d>>10,56320|d&1023))}}else e+=String.fromCharCode(d)}}function E(a){return ma(D,a)}
function ha(a,b,e){var d=D;if(0<e){e=b+e-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var h=a.charCodeAt(++f);g=65536+((g&1023)<<10)|h&1023}if(127>=g){if(b>=e)break;d[b++]=g}else{if(2047>=g){if(b+1>=e)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=e)break;d[b++]=224|g>>12}else{if(2097151>=g){if(b+3>=e)break;d[b++]=240|g>>18}else{if(67108863>=g){if(b+4>=e)break;d[b++]=248|g>>24}else{if(b+5>=e)break;d[b++]=252|g>>30;d[b++]=128|g>>24&63}d[b++]=128|g>>18&63}d[b++]=128|g>>
12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0}}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function F(a,b){0<a%b&&(a+=b-a%b);return a}var buffer,C,D,na,oa,G,H,pa,qa;function ra(){c.HEAP8=C=new Int8Array(buffer);c.HEAP16=na=new Int16Array(buffer);c.HEAP32=G=new Int32Array(buffer);c.HEAPU8=D=new Uint8Array(buffer);c.HEAPU16=oa=new Uint16Array(buffer);c.HEAPU32=H=new Uint32Array(buffer);c.HEAPF32=pa=new Float32Array(buffer);c.HEAPF64=qa=new Float64Array(buffer)}
var I,J,sa,K,ta,ua,L;I=J=sa=K=ta=ua=L=0;c.reallocBuffer||(c.reallocBuffer=function(a){try{var b=C;var e=new ArrayBuffer(a);(new Int8Array(e)).set(b)}catch(d){return!1}return va(e)?e:!1});var wa;try{wa=Function.prototype.call.bind(Object.getOwnPropertyDescriptor(ArrayBuffer.prototype,"byteLength").get),wa(new ArrayBuffer(4))}catch(a){wa=function(b){return b.byteLength}}var xa=c.TOTAL_STACK||5242880,M=c.TOTAL_MEMORY||16777216;
M<xa&&A("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+M+"! (TOTAL_STACK="+xa+")");c.buffer?buffer=c.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(c.wasmMemory=new WebAssembly.Memory({initial:M/65536}),buffer=c.wasmMemory.buffer):buffer=new ArrayBuffer(M),c.buffer=buffer);ra();
function N(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var e=b.l;"number"===typeof e?void 0===b.b?c.dynCall_v(e):c.dynCall_vi(e,b.b):e(void 0===b.b?null:b.b)}}}var ya=[],za=[],Aa=[],Ba=[],Ca=[],Da=!1;function Ea(){var a=c.preRun.shift();ya.unshift(a)}var O=0,Fa=null,P=null;c.preloadedImages={};c.preloadedAudios={};function Q(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){return new Promise(function(a){a:{try{if(c.wasmBinary){var b=new Uint8Array(c.wasmBinary);break a}if(c.readBinary){b=c.readBinary(d);break a}throw"both async and sync fetching of the wasm failed";}catch(x){y(x)}b=void 0}a(b)})}function b(b){function e(a){h=a.exports;if(h.memory){a=h.memory;var b=c.buffer;a.byteLength<b.byteLength&&A("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);
c.buffer=buffer=a;ra()}c.asm=h;c.usingWasm=!0;O--;c.monitorRunDependencies&&c.monitorRunDependencies(O);0==O&&(null!==Fa&&(clearInterval(Fa),Fa=null),P&&(a=P,P=null,a()))}function f(a){e(a.instance)}function l(b){a().then(function(a){return WebAssembly.instantiate(a,g)}).then(b,function(a){A("failed to asynchronously prepare wasm: "+a);y(a)})}if("object"!==typeof WebAssembly)return A("no native wasm support detected"),!1;if(!(c.wasmMemory instanceof WebAssembly.Memory))return A("no native wasm Memory in use"),
!1;b.memory=c.wasmMemory;g.global={NaN:NaN,Infinity:Infinity};g["global.Math"]=Math;g.env=b;O++;c.monitorRunDependencies&&c.monitorRunDependencies(O);if(c.instantiateWasm)try{return c.instantiateWasm(g,e)}catch(Ua){return A("Module.instantiateWasm callback failed with error: "+Ua),!1}c.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||Q(d)||"function"!==typeof fetch?l(f):WebAssembly.instantiateStreaming(fetch(d,{credentials:"same-origin"}),g).then(f,function(a){A("wasm streaming compile failed: "+
a);A("falling back to ArrayBuffer instantiation");l(f)});return{}}var e="ColorQuantizer.wast",d="ColorQuantizer.wasm",f="ColorQuantizer.temp.asm.js";Q(e)||(e=t(e));Q(d)||(d=t(d));Q(f)||(f=t(f));var g={global:null,env:null,asm2wasm:ba,parent:c},h=null;c.asmPreload=c.asm;var k=c.reallocBuffer;c.reallocBuffer=function(a){if("asmjs"===m)var b=k(a);else a:{a=F(a,c.usingWasm?65536:16777216);var d=c.buffer.byteLength;if(c.usingWasm)try{b=-1!==c.wasmMemory.grow((a-d)/65536)?c.buffer=c.wasmMemory.buffer:null;
break a}catch(db){b=null;break a}b=void 0}return b};var m="";c.asm=function(a,d){if(!d.table){a=c.wasmTableSize;void 0===a&&(a=1024);var e=c.wasmMaxTableSize;d.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==e?new WebAssembly.Table({initial:a,maximum:e,element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):Array(a);c.wasmTable=d.table}d.memoryBase||(d.memoryBase=c.STATIC_BASE);d.tableBase||(d.tableBase=0);d=b(d);assert(d,"no binaryen method succeeded.");
return d}})();I=1024;J=I+5824;za.push({l:function(){Ga()}});c.STATIC_BASE=I;c.STATIC_BUMP=5824;J+=16;var R=0;function S(){R+=4;return G[R-4>>2]}var Ha={};function T(a,b){R=b;try{var e=S(),d=S(),f=S();a=0;T.f||(T.f=[null,[],[]],T.j=function(a,b){var d=T.f[a];assert(d);0===b||10===b?((1===a?z:A)(ma(d,0)),d.length=0):d.push(b)});for(b=0;b<f;b++){for(var g=G[d+8*b>>2],h=G[d+(8*b+4)>>2],k=0;k<h;k++)T.j(e,D[g+k]);a+=h}return a}catch(m){return"undefined"!==typeof FS&&m instanceof FS.c||y(m),-m.g}}
function Ia(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ja=void 0;function U(a){for(var b="";D[a];)b+=Ja[D[a++]];return b}var Ka={},La={},Ma={};function Na(a,b){if(void 0===a)a="_unknown";else{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var e=a.charCodeAt(0);a=48<=e&&57>=e?"_"+a:a}return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Oa(a){var b=Error,e=Na(a,function(b){this.name=a;this.message=b;b=Error(b).stack;void 0!==b&&(this.stack=this.toString()+"\n"+b.replace(/^Error(:[^\n]*)?\n/,""))});e.prototype=Object.create(b.prototype);e.prototype.constructor=e;e.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return e}var Pa=void 0;function V(a){throw new Pa(a);}
function W(a,b,e){e=e||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||V('type "'+d+'" must have a positive integer typeid pointer');if(La.hasOwnProperty(a)){if(e.s)return;V("Cannot register type '"+d+"' twice")}La[a]=b;delete Ma[a];Ka.hasOwnProperty(a)&&(b=Ka[a],delete Ka[a],b.forEach(function(a){a()}))}var Qa=[],X=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function Ra(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Qa.length?Qa.pop():X.length;X[b]={u:1,value:a};return b}}function Sa(a){return this.fromWireType(H[a>>2])}function Ta(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Va(a,b){switch(b){case 2:return function(a){return this.fromWireType(pa[a>>2])};case 3:return function(a){return this.fromWireType(qa[a>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Wa(a,b,e){switch(b){case 0:return e?function(a){return C[a]}:function(a){return D[a]};case 1:return e?function(a){return na[a>>1]}:function(a){return oa[a>>1]};case 2:return e?function(a){return G[a>>2]}:function(a){return H[a>>2]};default:throw new TypeError("Unknown integer type: "+a);}}for(var Xa=Array(256),Y=0;256>Y;++Y)Xa[Y]=String.fromCharCode(Y);Ja=Xa;Pa=c.BindingError=Oa("BindingError");c.InternalError=Oa("InternalError");
c.count_emval_handles=function(){for(var a=0,b=5;b<X.length;++b)void 0!==X[b]&&++a;return a};c.get_first_emval=function(){for(var a=5;a<X.length;++a)if(void 0!==X[a])return X[a];return null};var Ya=J;J=J+4+15&-16;L=Ya;sa=K=aa(J);ta=sa+xa;ua=aa(ta);G[L>>2]=ua;c.wasmTableSize=30;c.wasmMaxTableSize=30;c.h={};
c.i={abort:y,enlargeMemory:function(){var a=c.usingWasm?65536:16777216,b=2147483648-a;if(G[L>>2]>b)return!1;var e=M;for(M=Math.max(M,16777216);M<G[L>>2];)536870912>=M?M=F(2*M,a):M=Math.min(F((3*M+2147483648)/4,a),b);a=c.reallocBuffer(M);if(!a||a.byteLength!=M)return M=e,!1;c.buffer=buffer=a;ra();return!0},getTotalMemory:function(){return M},abortOnCannotGrowMemory:function(){y("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+M+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")},
___setErrNo:function(a){c.___errno_location&&(G[c.___errno_location()>>2]=a);return a},___syscall140:function(a,b){R=b;try{var e=Ha.m();S();var d=S(),f=S(),g=S();FS.w(e,d,g);G[f>>2]=e.position;e.o&&0===d&&0===g&&(e.o=null);return 0}catch(h){return"undefined"!==typeof FS&&h instanceof FS.c||y(h),-h.g}},___syscall146:T,___syscall6:function(a,b){R=b;try{var e=Ha.m();FS.close(e);return 0}catch(d){return"undefined"!==typeof FS&&d instanceof FS.c||y(d),-d.g}},__embind_register_bool:function(a,b,e,d,f){var g=
Ia(e);b=U(b);W(a,{name:b,fromWireType:function(a){return!!a},toWireType:function(a,b){return b?d:f},argPackAdvance:8,readValueFromPointer:function(a){if(1===e)var d=C;else if(2===e)d=na;else if(4===e)d=G;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(d[a>>g])},a:null})},__embind_register_emval:function(a,b){b=U(b);W(a,{name:b,fromWireType:function(a){var b=X[a].value;4<a&&0===--X[a].u&&(X[a]=void 0,Qa.push(a));return b},toWireType:function(a,b){return Ra(b)},argPackAdvance:8,
readValueFromPointer:Sa,a:null})},__embind_register_float:function(a,b,e){e=Ia(e);b=U(b);W(a,{name:b,fromWireType:function(a){return a},toWireType:function(a,b){if("number"!==typeof b&&"boolean"!==typeof b)throw new TypeError('Cannot convert "'+Ta(b)+'" to '+this.name);return b},argPackAdvance:8,readValueFromPointer:Va(b,e),a:null})},__embind_register_integer:function(a,b,e,d,f){function g(a){return a}b=U(b);-1===f&&(f=4294967295);var h=Ia(e);if(0===d){var k=32-8*e;g=function(a){return a<<k>>>k}}var m=
-1!=b.indexOf("unsigned");W(a,{name:b,fromWireType:g,toWireType:function(a,e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+Ta(e)+'" to '+this.name);if(e<d||e>f)throw new TypeError('Passing a number "'+Ta(e)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+f+"]!");return m?e>>>0:e|0},argPackAdvance:8,readValueFromPointer:Wa(b,h,0!==d),a:null})},__embind_register_memory_view:function(a,b,e){function d(a){a>>=
2;var b=H;return new f(b.buffer,b[a+1],b[a])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];e=U(e);W(a,{name:e,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{s:!0})},__embind_register_std_string:function(a,b){b=U(b);var e="std::string"===b;W(a,{name:b,fromWireType:function(a){var b=H[a>>2];if(e){var d=D[a+4+b],h=0;0!=d&&(h=d,D[a+4+b]=0);var k=a+4;for(d=0;d<=b;++d){var m=a+4+d;if(0==D[m]){k=E(k);if(void 0===l)var l=k;else l+=String.fromCharCode(0),
l+=k;k=m+1}}0!=h&&(D[a+4+b]=h)}else{l=Array(b);for(d=0;d<b;++d)l[d]=String.fromCharCode(D[a+4+d]);l=l.join("")}Z(a);return l},toWireType:function(a,b){b instanceof ArrayBuffer&&(b=new Uint8Array(b));var d="string"===typeof b;d||b instanceof Uint8Array||b instanceof Uint8ClampedArray||b instanceof Int8Array||V("Cannot pass non-string to std::string");var f=(e&&d?function(){for(var a=0,d=0;d<b.length;++d){var e=b.charCodeAt(d);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|b.charCodeAt(++d)&1023);127>=
e?++a:a=2047>=e?a+2:65535>=e?a+3:2097151>=e?a+4:67108863>=e?a+5:a+6}return a}:function(){return b.length})(),k=Za(4+f+1);H[k>>2]=f;if(e&&d)ha(b,k+4,f+1);else if(d)for(d=0;d<f;++d){var m=b.charCodeAt(d);255<m&&(Z(k),V("String has UTF-16 code units that do not fit in 8 bits"));D[k+4+d]=m}else for(d=0;d<f;++d)D[k+4+d]=b[d];null!==a&&a.push(Z,k);return k},argPackAdvance:8,readValueFromPointer:Sa,a:function(a){Z(a)}})},__embind_register_std_wstring:function(a,b,e){e=U(e);if(2===b){var d=function(){return oa};
var f=1}else 4===b&&(d=function(){return H},f=2);W(a,{name:e,fromWireType:function(a){for(var b=d(),e=H[a>>2],g=Array(e),l=a+4>>f,q=0;q<e;++q)g[q]=String.fromCharCode(b[l+q]);Z(a);return g.join("")},toWireType:function(a,e){var g=d(),h=e.length,l=Za(4+h*b);H[l>>2]=h;for(var q=l+4>>f,x=0;x<h;++x)g[q+x]=e.charCodeAt(x);null!==a&&a.push(Z,l);return l},argPackAdvance:8,readValueFromPointer:Sa,a:function(a){Z(a)}})},__embind_register_void:function(a,b){b=U(b);W(a,{v:!0,name:b,argPackAdvance:0,fromWireType:function(){},
toWireType:function(){}})},_emscripten_memcpy_big:function(a,b,e){D.set(D.subarray(b,b+e),a);return a},_exit:function(a){if(!c.noExitRuntime&&(B=!0,K=$a,N(Ba),c.onExit))c.onExit(a);c.quit(a,new w(a))},DYNAMICTOP_PTR:L,STACKTOP:K};var ab=c.asm(c.h,c.i,buffer);c.asm=ab;var Ga=c.__GLOBAL__sub_I_bind_cpp=function(){return c.asm.__GLOBAL__sub_I_bind_cpp.apply(null,arguments)};c.___getTypeName=function(){return c.asm.___getTypeName.apply(null,arguments)};
var va=c._emscripten_replace_memory=function(){return c.asm._emscripten_replace_memory.apply(null,arguments)},Z=c._free=function(){return c.asm._free.apply(null,arguments)};c._getImageThemeColor=function(){return c.asm._getImageThemeColor.apply(null,arguments)};
var Za=c._malloc=function(){return c.asm._malloc.apply(null,arguments)},fa=c.stackAlloc=function(){return c.asm.stackAlloc.apply(null,arguments)},ea=c.stackRestore=function(){return c.asm.stackRestore.apply(null,arguments)},da=c.stackSave=function(){return c.asm.stackSave.apply(null,arguments)};c.dynCall_vi=function(){return c.asm.dynCall_vi.apply(null,arguments)};c.asm=ab;
c.cwrap=function(a,b,e,d){e=e||[];var f=e.every(function(a){return"number"===a});return"string"!==b&&f&&!d?ca(a):function(){var d=e,f=arguments,k=ca(a),m=[],l=0;if(f)for(var q=0;q<f.length;q++){var x=ja[d[q]];x?(0===l&&(l=da()),m[q]=x(f[q])):m[q]=f[q]}d=k.apply(null,m);d="string"===b?ka(d):"boolean"===b?!!d:d;0!==l&&ea(l);return d}};c.UTF8ToString=E;c.then=function(a){if(c.calledRun)a(c);else{var b=c.onRuntimeInitialized;c.onRuntimeInitialized=function(){b&&b();a(c)}}return c};
function w(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}w.prototype=Error();w.prototype.constructor=w;var $a;P=function bb(){c.calledRun||cb();c.calledRun||(P=bb)};
function cb(){function a(){if(!c.calledRun&&(c.calledRun=!0,!B)){Da||(Da=!0,N(za));N(Aa);if(c.onRuntimeInitialized)c.onRuntimeInitialized();if(c.postRun)for("function"==typeof c.postRun&&(c.postRun=[c.postRun]);c.postRun.length;){var a=c.postRun.shift();Ca.unshift(a)}N(Ca)}}if(!(0<O)){if(c.preRun)for("function"==typeof c.preRun&&(c.preRun=[c.preRun]);c.preRun.length;)Ea();N(ya);0<O||c.calledRun||(c.setStatus?(c.setStatus("Running..."),setTimeout(function(){setTimeout(function(){c.setStatus("")},1);
a()},1)):a())}}c.run=cb;function y(a){if(c.onAbort)c.onAbort(a);void 0!==a?(z(a),A(a),a=JSON.stringify(a)):a="";B=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}c.abort=y;if(c.preInit)for("function"==typeof c.preInit&&(c.preInit=[c.preInit]);0<c.preInit.length;)c.preInit.pop()();c.noExitRuntime=!0;cb();


  return Module;
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
    module.exports = Module;
  else if (typeof define === 'function' && define['amd'])
    define([], function() { return Module; });
  else if (typeof exports === 'object')
    exports["Module"] = Module;
  