
var Module = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  return (
function(Module) {
  Module = Module || {};

var c;c||(c=typeof Module !== 'undefined' ? Module : {});var m={},n;for(n in c)c.hasOwnProperty(n)&&(m[n]=c[n]);c.arguments=[];c.thisProgram="./this.program";c.quit=function(a,b){throw b;};c.preRun=[];c.postRun=[];var p="";function u(a){return c.locateFile?c.locateFile(a,p):p+a}p=__dirname+"/";var v,w;c.read=function(a,b){v||(v=require("fs"));w||(w=require("path"));a=w.normalize(a);a=v.readFileSync(a);return b?a:a.toString()};
c.readBinary=function(a){a=c.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(c.thisProgram=process.argv[1].replace(/\\/g,"/"));c.arguments=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof x))throw a;});process.on("unhandledRejection",y);c.quit=function(a){process.exit(a)};c.inspect=function(){return"[Emscripten Module object]"};
var aa=c.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),z=c.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||aa);for(n in m)m.hasOwnProperty(n)&&(c[n]=m[n]);m=void 0;function ba(a){var b=A;A=A+a+15&-16;return b}function ca(a){var b=B[C>>2];a=b+a+15&-16;B[C>>2]=a;return a>=D&&!da()?(B[C>>2]=b,0):b}function ea(a){var b;b||(b=16);return Math.ceil(a/b)*b}
var fa={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},tempRet0=0,ha=!1;function assert(a,b){a||y("Assertion failed: "+b)}function ia(a){var b=c["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
var na={stackSave:function(){ja()},stackRestore:function(){ka()},arrayToC:function(a){var b=la(a.length);E.set(a,b);return b},stringToC:function(a){var b=0;if(null!==a&&void 0!==a&&0!==a){var d=(a.length<<2)+1;b=la(d);ma(a,F,b,d)}return b}},oa={string:na.stringToC,array:na.arrayToC};
function pa(a){var b;if(0===b||!a)return"";for(var d=0,e,f=0;;){e=F[a+f>>0];d|=e;if(0==e&&!b)break;f++;if(b&&f==b)break}b||(b=f);e="";if(128>d){for(;0<b;)d=String.fromCharCode.apply(String,F.subarray(a,a+Math.min(b,1024))),e=e?e+d:d,a+=1024,b-=1024;return e}return qa(a)}var ra="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function sa(a,b){for(var d=b;a[d];)++d;if(16<d-b&&a.subarray&&ra)return ra.decode(a.subarray(b,d));for(d="";;){var e=a[b++];if(!e)return d;if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;if(224==(e&240))e=(e&15)<<12|f<<6|g;else{var k=a[b++]&63;if(240==(e&248))e=(e&7)<<18|f<<12|g<<6|k;else{var h=a[b++]&63;if(248==(e&252))e=(e&3)<<24|f<<18|g<<12|k<<6|h;else{var r=a[b++]&63;e=(e&1)<<30|f<<24|g<<18|k<<12|h<<6|r}}}65536>e?d+=String.fromCharCode(e):(e-=
65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}}function qa(a){return sa(F,a)}
function ma(a,b,d,e){if(0<e){e=d+e-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var k=a.charCodeAt(++f);g=65536+((g&1023)<<10)|k&1023}if(127>=g){if(d>=e)break;b[d++]=g}else{if(2047>=g){if(d+1>=e)break;b[d++]=192|g>>6}else{if(65535>=g){if(d+2>=e)break;b[d++]=224|g>>12}else{if(2097151>=g){if(d+3>=e)break;b[d++]=240|g>>18}else{if(67108863>=g){if(d+4>=e)break;b[d++]=248|g>>24}else{if(d+5>=e)break;b[d++]=252|g>>30;b[d++]=128|g>>24&63}b[d++]=128|g>>18&63}b[d++]=128|g>>12&63}b[d++]=
128|g>>6&63}b[d++]=128|g&63}}b[d]=0}}function ta(a){for(var b=0,d=0;d<a.length;++d){var e=a.charCodeAt(d);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++d)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:2097151>=e?b+4:67108863>=e?b+5:b+6}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");var ua=65536,va=16777216,wa=16777216;function xa(a,b){0<a%b&&(a+=b-a%b);return a}var buffer,E,F,ya,za,B,G,Aa,Ba;
function Ca(){c.HEAP8=E=new Int8Array(buffer);c.HEAP16=ya=new Int16Array(buffer);c.HEAP32=B=new Int32Array(buffer);c.HEAPU8=F=new Uint8Array(buffer);c.HEAPU16=za=new Uint16Array(buffer);c.HEAPU32=G=new Uint32Array(buffer);c.HEAPF32=Aa=new Float32Array(buffer);c.HEAPF64=Ba=new Float64Array(buffer)}var H,A,I,Da,J,Ea,Fa,C;H=A=Da=J=Ea=Fa=C=0;I=!1;c.reallocBuffer||(c.reallocBuffer=function(a){try{var b=E;var d=new ArrayBuffer(a);(new Int8Array(d)).set(b)}catch(e){return!1}return Ga(d)?d:!1});
function da(){var a=c.usingWasm?ua:va,b=2147483648-a;if(B[C>>2]>b)return!1;var d=D;for(D=Math.max(D,wa);D<B[C>>2];)536870912>=D?D=xa(2*D,a):D=Math.min(xa((3*D+2147483648)/4,a),b);a=c.reallocBuffer(D);if(!a||a.byteLength!=D)return D=d,!1;c.buffer=buffer=a;Ca();return!0}var Ha;try{Ha=Function.prototype.call.bind(Object.getOwnPropertyDescriptor(ArrayBuffer.prototype,"byteLength").get),Ha(new ArrayBuffer(4))}catch(a){Ha=function(b){return b.byteLength}}
var Ia=c.TOTAL_STACK||5242880,D=c.TOTAL_MEMORY||16777216;D<Ia&&z("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+D+"! (TOTAL_STACK="+Ia+")");c.buffer?buffer=c.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(c.wasmMemory=new WebAssembly.Memory({initial:D/ua}),buffer=c.wasmMemory.buffer):buffer=new ArrayBuffer(D),c.buffer=buffer);Ca();
function K(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var d=b.P;"number"===typeof d?void 0===b.M?c.dynCall_v(d):c.dynCall_vi(d,b.M):d(void 0===b.M?null:b.M)}}}var Ja=[],Ka=[],La=[],Ma=[],Na=[],L=!1;function Oa(){var a=c.preRun.shift();Ja.unshift(a)}var M=0,Pa=null,N=null;c.preloadedImages={};c.preloadedAudios={};function O(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){return new Promise(function(a){a:{try{if(c.wasmBinary){var b=new Uint8Array(c.wasmBinary);break a}if(c.readBinary){b=c.readBinary(e);break a}throw"both async and sync fetching of the wasm failed";}catch(t){y(t)}b=void 0}a(b)})}function b(b){function d(a){k=a.exports;if(k.memory){a=k.memory;var b=c.buffer;a.byteLength<b.byteLength&&z("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);
c.buffer=buffer=a;Ca()}c.asm=k;c.usingWasm=!0;M--;c.monitorRunDependencies&&c.monitorRunDependencies(M);0==M&&(null!==Pa&&(clearInterval(Pa),Pa=null),N&&(a=N,N=null,a()))}function f(a){d(a.instance)}function h(b){a().then(function(a){return WebAssembly.instantiate(a,g)}).then(b,function(a){z("failed to asynchronously prepare wasm: "+a);y(a)})}if("object"!==typeof WebAssembly)return z("no native wasm support detected"),!1;if(!(c.wasmMemory instanceof WebAssembly.Memory))return z("no native wasm Memory in use"),
!1;b.memory=c.wasmMemory;g.global={NaN:NaN,Infinity:Infinity};g["global.Math"]=Math;g.env=b;M++;c.monitorRunDependencies&&c.monitorRunDependencies(M);if(c.instantiateWasm)try{return c.instantiateWasm(g,d)}catch(db){return z("Module.instantiateWasm callback failed with error: "+db),!1}c.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||O(e)||"function"!==typeof fetch?h(f):WebAssembly.instantiateStreaming(fetch(e,{credentials:"same-origin"}),g).then(f,function(a){z("wasm streaming compile failed: "+
a);z("falling back to ArrayBuffer instantiation");h(f)});return{}}var d="jpeg_encode.wast",e="jpeg_encode.wasm",f="jpeg_encode.temp.asm.js";O(d)||(d=u(d));O(e)||(e=u(e));O(f)||(f=u(f));var g={global:null,env:null,asm2wasm:fa,parent:c},k=null;c.asmPreload=c.asm;var h=c.reallocBuffer;c.reallocBuffer=function(a){if("asmjs"===r)var b=h(a);else a:{a=xa(a,c.usingWasm?ua:va);var d=c.buffer.byteLength;if(c.usingWasm)try{b=-1!==c.wasmMemory.grow((a-d)/65536)?c.buffer=c.wasmMemory.buffer:null;break a}catch(pb){b=
null;break a}b=void 0}return b};var r="";c.asm=function(a,d){if(!d.table){a=c.wasmTableSize;void 0===a&&(a=1024);var e=c.wasmMaxTableSize;d.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==e?new WebAssembly.Table({initial:a,maximum:e,element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):Array(a);c.wasmTable=d.table}d.__memory_base||(d.__memory_base=c.STATIC_BASE);d.__table_base||(d.__table_base=0);d=b(d);assert(d,"no binaryen method succeeded.");
return d}})();H=1024;A=H+14096;Ka.push({P:function(){Qa()}},{P:function(){Ra()}});c.STATIC_BASE=H;c.STATIC_BUMP=14096;var Sa=A;A+=16;var P={};
function Ta(a){if(Ta.K){var b=B[a>>2];var d=B[b>>2]}else Ta.K=!0,P.USER=P.LOGNAME="web_user",P.PATH="/",P.PWD="/",P.HOME="/home/web_user",P.LANG="C.UTF-8",P._=c.thisProgram,d=I?L?Q(1024):ca(1024):ba(1024),b=I?L?Q(256):ca(256):ba(256),B[b>>2]=d,B[a>>2]=b;a=[];var e=0,f;for(f in P)if("string"===typeof P[f]){var g=f+"="+P[f];a.push(g);e+=g.length}if(1024<e)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(f=0;f<a.length;f++){e=g=a[f];for(var k=d,h=0;h<e.length;++h)E[k++>>0]=e.charCodeAt(h);
E[k>>0]=0;B[b+4*f>>2]=d;d+=g.length+1}B[b+4*a.length>>2]=0}var Ua=[null,[],[]],R=0;function S(){R+=4;return B[R-4>>2]}var Va={};function Wa(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Xa=void 0;function T(a){for(var b="";F[a];)b+=Xa[F[a++]];return b}var Ya={},Za={},$a={};
function ab(a,b){if(void 0===a)a="_unknown";else{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var d=a.charCodeAt(0);a=48<=d&&57>=d?"_"+a:a}return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function bb(a){var b=Error,d=ab(a,function(b){this.name=a;this.message=b;b=Error(b).stack;void 0!==b&&(this.stack=this.toString()+"\n"+b.replace(/^Error(:[^\n]*)?\n/,""))});d.prototype=Object.create(b.prototype);d.prototype.constructor=d;d.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return d}var cb=void 0;function U(a){throw new cb(a);}
function V(a,b,d){d=d||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var e=b.name;a||U('type "'+e+'" must have a positive integer typeid pointer');if(Za.hasOwnProperty(a)){if(d.V)return;U("Cannot register type '"+e+"' twice")}Za[a]=b;delete $a[a];Ya.hasOwnProperty(a)&&(b=Ya[a],delete Ya[a],b.forEach(function(a){a()}))}var eb=[],W=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function fb(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=eb.length?eb.pop():W.length;W[b]={W:1,value:a};return b}}function gb(a){return this.fromWireType(G[a>>2])}function hb(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function ib(a,b){switch(b){case 2:return function(a){return this.fromWireType(Aa[a>>2])};case 3:return function(a){return this.fromWireType(Ba[a>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function jb(a,b,d){switch(b){case 0:return d?function(a){return E[a]}:function(a){return F[a]};case 1:return d?function(a){return ya[a>>1]}:function(a){return za[a>>1]};case 2:return d?function(a){return B[a>>2]}:function(a){return G[a>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function X(a){if(0===a)return 0;a=pa(a);if(!P.hasOwnProperty(a))return 0;X.K&&Y(X.K);a=P[a];var b=ta(a)+1,d=Q(b);d&&ma(a,E,d,b);X.K=d;return X.K}for(var kb=Array(256),Z=0;256>Z;++Z)kb[Z]=String.fromCharCode(Z);
Xa=kb;cb=c.BindingError=bb("BindingError");c.InternalError=bb("InternalError");c.count_emval_handles=function(){for(var a=0,b=5;b<W.length;++b)void 0!==W[b]&&++a;return a};c.get_first_emval=function(){for(var a=5;a<W.length;++a)if(void 0!==W[a])return W[a];return null};C=ba(4);Da=J=ea(A);Ea=Da+Ia;Fa=ea(Ea);B[C>>2]=Fa;I=!0;c.wasmTableSize=174;c.wasmMaxTableSize=174;c.R={};
c.S={g:y,y:da,r:function(){return D},e:function(a){tempRet0=a},d:function(){return tempRet0},p:function(){y("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+D+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")},o:Ta,k:function(a){c.___errno_location&&(B[c.___errno_location()>>2]=a);return a},
n:function(a,b){R=b;try{var d=Va.T();S();var e=S(),f=S(),g=S();FS.Y(d,e,g);B[f>>2]=d.position;d.U&&0===e&&0===g&&(d.U=null);return 0}catch(k){return"undefined"!==typeof FS&&k instanceof FS.N||y(k),-k.O}},j:function(a,b){R=b;try{var d=S(),e=S(),f=S();for(b=a=0;b<f;b++){for(var g=B[e+8*b>>2],k=B[e+(8*b+4)>>2],h=0;h<k;h++){var r=d,l=F[g+h],q=Ua[r];assert(q);0===l||10===l?((1===r?aa:z)(sa(q,0)),q.length=0):q.push(l)}a+=k}return a}catch(t){return"undefined"!==typeof FS&&t instanceof FS.N||y(t),-t.O}},
x:function(a,b){R=b;try{var d=Va.T();FS.close(d);return 0}catch(e){return"undefined"!==typeof FS&&e instanceof FS.N||y(e),-e.O}},w:function(a,b,d,e,f){var g=Wa(d);b=T(b);V(a,{name:b,fromWireType:function(a){return!!a},toWireType:function(a,b){return b?e:f},argPackAdvance:8,readValueFromPointer:function(a){if(1===d)var e=E;else if(2===d)e=ya;else if(4===d)e=B;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(e[a>>g])},L:null})},v:function(a,b){b=T(b);V(a,{name:b,fromWireType:function(a){var b=
W[a].value;4<a&&0===--W[a].W&&(W[a]=void 0,eb.push(a));return b},toWireType:function(a,b){return fb(b)},argPackAdvance:8,readValueFromPointer:gb,L:null})},m:function(a,b,d){d=Wa(d);b=T(b);V(a,{name:b,fromWireType:function(a){return a},toWireType:function(a,b){if("number"!==typeof b&&"boolean"!==typeof b)throw new TypeError('Cannot convert "'+hb(b)+'" to '+this.name);return b},argPackAdvance:8,readValueFromPointer:ib(b,d),L:null})},h:function(a,b,d,e,f){function g(a){return a}b=T(b);-1===f&&(f=4294967295);
var k=Wa(d);if(0===e){var h=32-8*d;g=function(a){return a<<h>>>h}}var r=-1!=b.indexOf("unsigned");V(a,{name:b,fromWireType:g,toWireType:function(a,d){if("number"!==typeof d&&"boolean"!==typeof d)throw new TypeError('Cannot convert "'+hb(d)+'" to '+this.name);if(d<e||d>f)throw new TypeError('Passing a number "'+hb(d)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+e+", "+f+"]!");return r?d>>>0:d|0},argPackAdvance:8,readValueFromPointer:jb(b,k,0!==e),
L:null})},f:function(a,b,d){function e(a){a>>=2;var b=G;return new f(b.buffer,b[a+1],b[a])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];d=T(d);V(a,{name:d,fromWireType:e,argPackAdvance:8,readValueFromPointer:e},{V:!0})},l:function(a,b){b=T(b);var d="std::string"===b;V(a,{name:b,fromWireType:function(a){var b=G[a>>2];if(d){var e=F[a+4+b],k=0;0!=e&&(k=e,F[a+4+b]=0);var h=a+4;for(e=0;e<=b;++e){var r=a+4+e;if(0==F[r]){h=qa(h);if(void 0===l)var l=
h;else l+=String.fromCharCode(0),l+=h;h=r+1}}0!=k&&(F[a+4+b]=k)}else{l=Array(b);for(e=0;e<b;++e)l[e]=String.fromCharCode(F[a+4+e]);l=l.join("")}Y(a);return l},toWireType:function(a,b){b instanceof ArrayBuffer&&(b=new Uint8Array(b));var e="string"===typeof b;e||b instanceof Uint8Array||b instanceof Uint8ClampedArray||b instanceof Int8Array||U("Cannot pass non-string to std::string");var f=(d&&e?function(){return ta(b)}:function(){return b.length})(),h=Q(4+f+1);G[h>>2]=f;if(d&&e)ma(b,F,h+4,f+1);else if(e)for(e=
0;e<f;++e){var r=b.charCodeAt(e);255<r&&(Y(h),U("String has UTF-16 code units that do not fit in 8 bits"));F[h+4+e]=r}else for(e=0;e<f;++e)F[h+4+e]=b[e];null!==a&&a.push(Y,h);return h},argPackAdvance:8,readValueFromPointer:gb,L:function(a){Y(a)}})},u:function(a,b,d){d=T(d);if(2===b){var e=function(){return za};var f=1}else 4===b&&(e=function(){return G},f=2);V(a,{name:d,fromWireType:function(a){for(var b=e(),d=G[a>>2],g=Array(d),l=a+4>>f,q=0;q<d;++q)g[q]=String.fromCharCode(b[l+q]);Y(a);return g.join("")},
toWireType:function(a,d){var g=e(),k=d.length,l=Q(4+k*b);G[l>>2]=k;for(var q=l+4>>f,t=0;t<k;++t)g[q+t]=d.charCodeAt(t);null!==a&&a.push(Y,l);return l},argPackAdvance:8,readValueFromPointer:gb,L:function(a){Y(a)}})},t:function(a,b){b=T(b);V(a,{X:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},s:function(a,b,d){F.set(F.subarray(b,b+d),a);return a},i:function(a){if(!c.noExitRuntime&&(ha=!0,J=lb,K(Ma),c.onExit))c.onExit(a);c.quit(a,new x(a))},q:X,a:C,b:Sa,c:J};
var mb=c.asm(c.R,c.S,buffer);c.asm=mb;var Qa=c.__GLOBAL__sub_I_bind_cpp=function(){return c.asm.z.apply(null,arguments)},Ra=c.___emscripten_environ_constructor=function(){return c.asm.A.apply(null,arguments)};c.___getTypeName=function(){return c.asm.B.apply(null,arguments)};var Ga=c._emscripten_replace_memory=function(){return c.asm._emscripten_replace_memory.apply(null,arguments)},Y=c._free=function(){return c.asm.C.apply(null,arguments)};c._get_jpeg_size=function(){return c.asm.D.apply(null,arguments)};
c._jpeg_encode=function(){return c.asm.E.apply(null,arguments)};var Q=c._malloc=function(){return c.asm.F.apply(null,arguments)},la=c.stackAlloc=function(){return c.asm.H.apply(null,arguments)},ka=c.stackRestore=function(){return c.asm.I.apply(null,arguments)},ja=c.stackSave=function(){return c.asm.J.apply(null,arguments)};c.dynCall_vi=function(){return c.asm.G.apply(null,arguments)};c.asm=mb;
c.cwrap=function(a,b,d,e){d=d||[];var f=d.every(function(a){return"number"===a});return"string"!==b&&f&&!e?ia(a):function(){var e=d,f=arguments,h=ia(a),r=[],l=0;if(f)for(var q=0;q<f.length;q++){var t=oa[e[q]];t?(0===l&&(l=ja()),r[q]=t(f[q])):r[q]=f[q]}e=h.apply(null,r);e="string"===b?pa(e):"boolean"===b?!!e:e;0!==l&&ka(l);return e}};c.UTF8ToString=qa;c.then=function(a){if(c.calledRun)a(c);else{var b=c.onRuntimeInitialized;c.onRuntimeInitialized=function(){b&&b();a(c)}}return c};
function x(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}x.prototype=Error();x.prototype.constructor=x;var lb;N=function nb(){c.calledRun||ob();c.calledRun||(N=nb)};
function ob(){function a(){if(!c.calledRun&&(c.calledRun=!0,!ha)){L||(L=!0,K(Ka));K(La);if(c.onRuntimeInitialized)c.onRuntimeInitialized();if(c.postRun)for("function"==typeof c.postRun&&(c.postRun=[c.postRun]);c.postRun.length;){var a=c.postRun.shift();Na.unshift(a)}K(Na)}}if(!(0<M)){if(c.preRun)for("function"==typeof c.preRun&&(c.preRun=[c.preRun]);c.preRun.length;)Oa();K(Ja);0<M||c.calledRun||(c.setStatus?(c.setStatus("Running..."),setTimeout(function(){setTimeout(function(){c.setStatus("")},1);
a()},1)):a())}}c.run=ob;function y(a){if(c.onAbort)c.onAbort(a);void 0!==a?(aa(a),z(a),a=JSON.stringify(a)):a="";ha=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}c.abort=y;if(c.preInit)for("function"==typeof c.preInit&&(c.preInit=[c.preInit]);0<c.preInit.length;)c.preInit.pop()();c.noExitRuntime=!0;ob();


  return Module;
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
    module.exports = Module;
  else if (typeof define === 'function' && define['amd'])
    define([], function() { return Module; });
  else if (typeof exports === 'object')
    exports["Module"] = Module;
  